const data={
products:[
{
    _id:'1',
    name:'Nike Slim Shirt',
    category:'Shirts',
    image:'/images/product-1.jpg',
    price:99,
    brand:'Nike',
    rating:4,
    numReviews:10,
    description:'high quality product',
},
{
    _id:'2',
    name:'Adidas Slim Shirt',
    category:'Shirts',
    image:'/images/product-2.jpg',
    price:65,
    brand:'Adidas',
    rating:3,
    numReviews:9,
    description:'high quality product',
},
{
    _id:'3',
    name:'puma Shirt',
    category:'Shirts',
    image:'/images/product-1.jpg',
    price:220,
    brand:'Nike',
    rating:5,
    numReviews:6,
    description:'high quality product',
},
{
    _id:'4',
    name:'Nike New Slim ',
    category:'Shirts',
    image:'/images/product-2.jpg',
    price:80,
    brand:'Nike',
    rating:3.5,
    numReviews:10,
    description:'high quality product',
},
{
    _id:'5',
    name:'SK Shirt',
    category:'Shirts',
    image:'/images/product-1.jpg',
    price:300,
    brand:'SK',
    rating:5,
    numReviews:10,
    description:'high quality product',
},
{
    _id:'6',
    name:'icon shirts',
    category:'Shirts',
    image:'/images/product-2.jpg',
    price:160,
    brand:'icon',
    rating:4.5,
    numReviews:10,
    description:'high quality product',
},
{
    _id:'7',
    name:'Adidas pro',
    category:'Shirts',
    image:'/images/product-2.jpg',
    price:99,
    brand:'Adidas pro',
    rating:4,
    numReviews:4,
    description:'high quality product',
},
{
    _id:'8',
    name:'Lecoste Free Shirt',
    category:'Shirts',
    image:'/images/product-1.jpg',
    price:220,
    brand:'Lecoste',
    rating:4.5,
    numReviews:10,
    description:'high quality product',
},
{
    _id:'9',
    name:'Lecoste pro',
    category:'pants',
    image:'/images/product-2.jpg',
    price:60,
    brand:'Lecoste pro',
    rating:2.5,
    numReviews:2,
    description:'high quality product',
},
]
}

export default data;